config/routes.rb
Rails.application.routes.draw do
  root to: 'recipes#index'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users, except: :new
  resources :recipes do
    resources :instructions
    resources :ingredients
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :instructions, dependent: :destroy
  accepts_nested_attributes_for :instructions, reject_if: lambda { |attributes| attributes['body'].blank? },
                                               allow_destroy: true

  has_many :ingredients, dependent: :destroy

  accepts_nested_attributes_for :ingredients, reject_if: lambda { |attributes| attributes['amount'].blank? },
                                              allow_destroy: true

  MAX_LENGTH_OF_TITLE = 40
  MAX_LENGTH_OF_DESCRITPION = 800
  validates :title, presence: true, length: { maximum: MAX_LENGTH_OF_TITLE }
  validates :description, presence: true, length: { maximum: MAX_LENGTH_OF_DESCRITPION }
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :logged_in_user, except: [:index, :show]
  before_action :set_params, only: [:show, :edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
    6.times { @recipe.ingredients.build }
    4.times { @recipe.instructions.build }
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    if @recipe.save
      redirect_to recipe_path(@recipe)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to @recipe
    else
      render :edit
    end
  end

  def destroy
    if @recipe.destroy
      flash[:danger] = 'Recipe deleted!'
      redirect_to root_path
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :description, ingredients_attributes: [:id, :amount, :user_id, :_destroy],
                                   instructions_attributes: [:id, :step, :body, :user_id, :_destroy])
  end

  def set_params
    @recipe = Recipe.find(params[:id])
  end

  def require_same_user
    unless current_user?(@recipe.user)
      flash[:danger] = 'You must be current user!'
      redirect_to root_path
    end
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= render 'shared/errors', object: recipe %>
<%= form_with model: recipe, local: true do |form| %>
  <div class="tile is-ancestor">
    <div class="tile is-vertical is-8">
      <div class="tile">
        <div class="tile is-parent">
          <article class="tile is-child notification is-caffe-light">
            <h1 class="title">Add Recipe</h1>
            <ul style="list-style: none;">
              <li><%= form.text_field :title, class:"input", placeholder: "Add Title of Recipe" %></li>
              <li><%= form.text_area :description, class:"input", rows:"30", placeholder: "Add Description of Recipe"  %></li>
            </ul>
          </article>
        </div>
      </div>
      <div class="tile is-parent">
        <article class="tile is-child notification is-caffe">
          <p class="title">Add Instruction</p>
          <div class="content">
            <%= form.fields_for :instructions do |builder| %>
              <% render 'instructions/nested_form', n: builder %>
            <% end %>
          </div>
        </article>
      </div>
    </div>
    <div class="tile is-parent">
      <article class="tile is-child notification is-caffe-light">
        <div class="content">
          <p class="title">Add Ingredients</p>
          <div class="content">
            <%= form.fields_for :ingredients do |builder| %>
              <%= render 'ingredients/nested_form', f: builder%>
            <% end %>
          </div>
        </div>
      </article>
    </div>
  </div>
  <footer class="card-footer">
    <%= form.submit button,  class:"card-footer-item is-caffe-light" %>
    <%= link_to 'Cancel', cancel ,class:"card-footer-item is-caffe" %>
  </footer>
<% end %>

app/views/recipes/_recipe.html.erb
<div class="container">
  <div class="columns">
    <div class="column is-6 is-offset-3">
      <div class="card">
        <%= link_to recipe_path(recipe) do %>
          <header class="card-header">
              <p class="card-header-title is-caffe-light">
                  <%= recipe.title %>
              </p>
          </header>
          <div class="card-content">
              <div class="content text-caffe">
                  <%= recipe.description %>
              </div>
          </div>
        <% end %>
         <footer class="card-footer">
           <p class="card-header-title is-caffe-light">
              <%= link_to user_path(recipe.user), class: "is-caffe-light" do %>
                by: <%= recipe.user.username %>
              <% end %>
           </p>
         <p class="card-header-left is-caffe-light"> <%= time_ago_in_words(recipe.created_at)%></p>
        </footer>
          <footer class="card-footer">
            <%= link_to 'Show', recipe_path(recipe), class:"card-footer-item is-caffe" %>
              <% if logged_in? && current_user?(recipe.user) %>
                <%= link_to 'Edit', edit_recipe_path(recipe), class:"card-footer-item is-caffe-light" %>
                <%= link_to 'Delete', recipe_path(recipe), method: :delete, data: { confirm: "Are you sure?" },
                                      class:"card-footer-item is-caffe" %>
              <% end %>
          </footer>
        </div>
     </div>
  </div>
</div>

app/views/recipes/edit.html.erb
<%= render 'form', recipe: @recipe, 
                   button: "Update Recipe", 
                   cancel: recipe_path(@recipe) %>

app/views/recipes/index.html.erb
<%= render @recipes %>

app/views/recipes/new.html.erb
<%= render 'form', recipe: @recipe,
                   button: "Save Recipe",
                   cancel: root_path %>

app/views/recipes/show.html.erb
<%= link_to user_path(@recipe.user), class: "is-caffe-light" do %>
  by: <%= @recipe.user.full_name %>
<% end %>
<div class="tile is-ancestor">
  <div class="tile is-vertical is-8">
    <div class="tile">
      <div class="tile is-parent">
        <article class="tile is-child notification is-caffe-light">
          <p class="title"><%= @recipe.title %></p>
            <p class="text"><%= @recipe.description %></p>
        </article>
      </div>
    </div>
    <div class="tile is-parent">
      <article class="tile is-child notification is-caffe">
        <p class="title">Instruction</p>
        <% if logged_in? && current_user?(@recipe.user) %>
          <p class="subtitle"> <%= link_to 'Add more instructions', new_recipe_instruction_path(@recipe, @instruction)%></p>
        <% end %>
        <div class="content">
            <%= render "instructions/instruction", recipe: @recipe, instruction: @instruction %>
        </div>
      </article>
    </div>
  </div>
  <div class="tile is-parent">
    <article class="tile is-child notification is-caffe-light">
      <div class="content">
        <p class="title">Ingredients</p>
        <% if logged_in? && current_user?(@recipe.user) %>
          <p class="subtitle"> <%= link_to 'Add more ingredients', new_recipe_ingredient_path(@recipe, @ingredient)%></p>
        <% end %>
        <div class="content">
           <%= render 'ingredients/ingredient', recipe: @recipe, ingredient: @ingredient%>
        </div>
      </div>
    </article>
  </div>
</div>
  <%= link_to "Back", root_path, class:"card-footer-item is-caffe"%>
<% if logged_in? && current_user?(@recipe.user) %>
  <%= link_to 'Edit', edit_recipe_path(@recipe), class:"card-footer-item is-caffe-light" %>
  <%= link_to 'Delete', recipe_path(@recipe), method: :delete, data: { confirm: "Are you sure?" },
                        class:"card-footer-item is-caffe" %>
<% end %>