config/routes.rb
Rails.application.routes.draw do
  root to: 'recipes#index'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users, except: :new
  resources :recipes do
    resources :instructions
    resources :ingredients
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :user
  belongs_to :recipe

  MAX_LENGTH_OF_AMOUNT = 200

  validates :amount, presence: true, length: { maximum: MAX_LENGTH_OF_AMOUNT }
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :logged_in_user
  before_action :set_params, only: [:show, :edit, :update, :destroy]
  before_action :require_same_user, except: :show
  def new
    @recipe = Recipe.find(params[:recipe_id])
    @ingredient = @recipe.ingredients.build
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @ingredient = @recipe.ingredients.build(ingredient_params)
    @ingredient.user = current_user

    if @ingredient.save
      redirect_to @ingredient.recipe
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @ingredient.update(ingredient_params)
      redirect_to recipe_path(@recipe, @ingredient)
    else
      render :new
    end
  end

  def destroy
    if @ingredient.destroy
      redirect_to recipe_path(@recipe, @ingredient)
    end
  end

  private

  def ingredient_params
    params.require(:ingredient).permit(:amount)
  end

  def set_params
    @recipe = Recipe.find(params[:recipe_id])
    @ingredient = Ingredient.find(params[:id])
  end

  def require_same_user
    unless current_user?(@ingredient.user)
      flash[:danger] = 'You must be current user!'
      redirect_to root_path
    end
  end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_form.html.erb
<%= form_with model: [recipe, ingredient], local: true do |form| %>
<div class="container">
    <div class="columns is-multiline">
      <div class="column is-6 is-offset-3">
        <div class="content is-size-3">
            <div class="field">
                <p class="control has-icons-left has-icons-right">
                    <%= form.text_field :amount , class: "input", placeholder: "Amount" %>
                </p>
            </div>
            <div class="field">
                <p class="control">
                    <%= form.submit "Add", class: "button is-caffe" %>
                </p>
            </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/ingredients/_ingredient.html.erb
<ul>
  <% recipe.ingredients.each do |f| %>
    <li><%= f.amount %></li>
    <% if logged_in? && current_user?(f.user) %>  
      <%= link_to "edit", edit_recipe_ingredient_url(recipe, f)%>
      <%= link_to "remove", [recipe, f], method: :delete %>
    <% end %>
    <hr class="is-caffe">
  <% end %>
</ul>

app/views/ingredients/_nested_form.html.erb
<ul style="list-style: none;">
  <li><%= f.hidden_field :user_id, value: current_user.id %></li>
  <li><%= f.text_field :amount, class:"input", placeholder: "Add Ingredients" %></li>
  <li><%= f.check_box :_destroy %>
      <%= f.label :_destroy, "remove"%>
  </li>
</ul>

app/views/ingredients/edit.html.erb
<%= render 'shared/errors', object: @ingredient %>
<%= render 'form', recipe: @recipe, ingredient: @ingredient %>

app/views/ingredients/new.html.erb
<h1 class="title has-text-centered"> Recipe Ingredients </h1>
<%= render 'shared/errors', object: @ingredient %>
<%= render 'form', recipe: @recipe, ingredient: @ingredient %>

app/views/ingredients/show.html.erb
<%= @ingredient.amount %>