config/routes.rb
Rails.application.routes.draw do
  root to: 'recipes#index'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users, except: :new
  resources :recipes do
    resources :instructions
    resources :ingredients
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<hr class="is-caffe">
<footer class="footer">
  <div class="content has-text-centered">
    <p>
      <strong>Hommemade Recipe</strong> by <a href="https://github.com/oselimi">Oselim94 Team</a>. Best programming commpany!
    </p>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
      <%= link_to root_path do %>
        <h1 class="title">Homemade Recipe</h1>
      <% end %>
  </div>
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
        <% if logged_in? %>
          <%= link_to new_recipe_path, class: "button is-caffe" do %>
            <strong><i class="fa fa-plus btn"></i></strong>
          <% end %>
          <%= link_to logout_path, method: :delete, class: "button is-caffe-light" do %>
            <strong><i class="fa fa-times-circle btn"></i></strong>
          <% end %>
        <% else %>
          <%= link_to login_path, class: "button is-caffe-light" do %>
            <strong>Login</strong>
          <% end %>
          <%= link_to signup_path, class: "button is-caffe" do %>
            <strong>Signup</strong>
          <% end %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>
<hr class="is-caffe">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>with Love</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section class="section">
      <%= render 'layouts/navbar' %>
      <%= render 'shared/flash'%>
      <%= yield %>
      <br/><br/><br/>
      <%= render 'layouts/footer'%>
    </section>
  </body>
</html>